name: Expo Submit
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  publish:
    name: Submit lasted build to Stores
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - name: submit
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
        run: npx eas-cli submit --platform ios --non-interactive --latest --no-wait
